M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu24.04.1} date 2025-04-02T18:22:05+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-02T18:22:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X96.39Y-107.841
X109.04Y-109.916
M30
