[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --partition-table partitions.csv --monitor"


[env]
ESP_LOG = "debug"

[build]

rustflags = [
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C",
    "force-frame-pointers",
    "-C",
    "link-arg=-Tlinkall.x",
]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
