[package]
name = "door-controller"
version = "0.1.0"
authors = ["Erik Tesar <erik@erik-tesar.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "door-controller"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync", "embedded-storage"] }
anyhow = "1.0.97"
multer = { version = "3.1.0", default-features = false }
futures-core = { version = "0.3.31", default-features = false }

[build-dependencies]
embuild = "0.33"
